v2.0.8

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,7 +18,7 @@ jobs:
           - runs-on,runner=1cpu-linux-x64
           - runs-on,runner=gofast,image=custom
           - runs-on,runner=gofast,cpu=1
-          - runs-on,runner=1cpu-linux-x64,image=ubuntu22-base-arm64
+          - runs-on,runner=1cpu-linux-arm64,image=ubuntu22-base-arm64
           - runs-on,image=ubuntu22-docker-x64,spot=false
           - runs-on,runner=2cpu-linux-arm64,image=ubuntu22-full-arm64
           - runs-on,runner=2cpu-linux-arm64,ssh=false
@@ -29,7 +29,7 @@ jobs:
         with:
           persist-credentials: false
       - name: Check preinstall
-        run: test -f /tmp/preinstalled || true
+        run: test -f /tmp/preinstalled || echo "Preinstall not found"
       - name: Setup
         run: |
           sudo apt-get update -qq && sudo apt-get install build-essential -y
